# Generated by Django 4.1.1 on 2022-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='Image',
            field=models.FileField(upload_to='media'),
        ),
    ]
